name: go_triunfo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.0.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  provider: ^6.1.2
  #firebase_app_check: ^0.3.1+2
  phone_numbers_parser: ^9.0.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  #build_runner: ^2.4.12
  #freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

